<?php

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

$title = get_sub_field('title');
$subtitle = get_sub_field('subtitle');
$cards = [];
if (have_rows('card')) :
    while (have_rows('card')) : the_row();
        $cards[] = [
            'label'   => get_sub_field('label'),
            'title'   => get_sub_field('title'),
            'subtext' => get_sub_field('subtext'),
            'link'    => get_sub_field('link'),
        ];
    endwhile;
endif;

if (!empty($cards)) :
?>

<section class="ecosystem-section">
    <div class="header-content">
        <?php if ($title) : ?>
            <h2 class="title"><?php echo $title; ?></h2>
        <?php endif; ?>
        <?php if ($subtitle) : ?>
            <p class="subtitle"><?php echo $subtitle; ?></p>
        <?php endif; ?>
    </div>

    <div class="cards-container" id="ecosystem-cards-container">
        <!-- Arc visual helper -->
<!--        <div class="arc-line"></div>-->

        <?php foreach ($cards as $index => $card) : ?>

            <div class="card" data-index="<?php echo $index; ?>">
                <div class="corner-marks">
                    <div class="corner-mark top-left"></div>
                    <div class="corner-mark top-right"></div>
                    <div class="corner-mark bottom-left"></div>
                    <div class="corner-mark bottom-right"></div>
                </div>
                <?php if ($card['label']) : ?>
                    <div class="card-top"><?php echo esc_html($card['label']); ?></div>
                <?php endif; ?>
                <div class="card-content">
                    <?php if ($card['title']) : ?>
                        <h3 class="card-title"><?php echo esc_html($card['title']); ?></h3>
                    <?php endif; ?>
                    <?php if ($card['subtext']) : ?>
                        <p class="card-description"><?php echo esc_html($card['subtext']); ?></p>
                    <?php endif; ?>
                    <?php if (!empty($card['link']) && is_array($card['link'])) : ?>
                        <a href="<?php echo esc_url($card['link']['url']); ?>" 
                           target="<?php echo esc_attr($card['link']['target'] ?: '_self'); ?>" 
                           class="learn-more">
                           <?php echo esc_html($card['link']['title'] ?: 'Learn more'); ?> ↗
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="pagination" id="ecosystem-pagination">
        <!-- Dots generated by JS -->
    </div>
</section>

<style>
    .ecosystem-section {
        width: 100%;
        max-width: 1400px;
        position: relative;
        padding: 60px 20px;
        text-align: center;
        /*background: radial-gradient(circle at 70% 100%, rgba(0, 170, 80, 0.15) 0%, transparent 50%);*/
        margin: 0 auto;
        --bg-color: #020714;
        --text-color: #FFFFFF;
        --text-muted: #A6A7AB;
        --accent-green: #00AA50;
        --card-bg: rgba(255, 255, 255, 0.05);
        --card-border: rgba(255, 255, 255, 0.1);
        overflow: hidden;
    }

    .ecosystem-section .header-content {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        text-align: left;
        margin-bottom: 80px;
        padding: 0 10%;
    }

    .ecosystem-section .title {
        font-size: 48px;
        font-weight: 800;
        text-transform: uppercase;
        line-height: 1;
        max-width: 400px;
        margin: 0;
        color: var(--text-color);
    }

    .ecosystem-section .subtitle {
        font-size: 16px;
        color: var(--text-muted);
        max-width: 400px;
        line-height: 1.6;
        margin: 0;
    }

    .ecosystem-section .cards-container {
        position: relative;
        height: 700px;
        display: flex;
        justify-content: center;
        align-items: center;
        perspective: 1000px;
    }

    .ecosystem-section .card {
        position: absolute;
        width: 380px;
        height: 450px;
        background: linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.02) 100%);
        border: 1px solid var(--card-border);
        border-radius: 20px;
        padding: 40px;
        box-sizing: border-box;
        transition: all 0.6s cubic-bezier(0.23, 1, 0.32, 1);
        cursor: pointer;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        backdrop-filter: blur(0px);
        opacity: 1;
        z-index: 1;
        text-align: left;
    }

    /* Not in focus cards */
    .ecosystem-section .card:not(.active) {
        filter: blur(1px);
        opacity: 0.8;
        transform: scale(0.8);
    }

    .ecosystem-section .card.active {
        z-index: 10;
        background: linear-gradient(135deg, rgba(0, 170, 80, 0.2) 0%, rgba(2, 7, 20, 0.4) 100%);
        border-color: rgba(0, 170, 80, 0.3);
        box-shadow: 0 20px 50px rgba(0,0,0,0.5);
    }

    .ecosystem-section .card-top {
        font-size: 12px;
        text-transform: uppercase;
        letter-spacing: 2px;
        color: var(--accent-green);
        display: flex;
        align-items: center;
        gap: 10px;
    }

    /* The mock had this, keeping it for styling reference if needed */
    /* .card-top::after { content: ">> PRE IPO"; color: var(--text-muted); font-size: 10px; } */

    .ecosystem-section .card-content {
        margin-top: auto;
    }

    .ecosystem-section .card-title {
        font-size: 28px;
        margin: 0 0 10px 0;
        font-weight: 600;
        color: var(--text-color);
    }

    .ecosystem-section .card-description {
        font-size: 16px;
        color: var(--text-muted);
        line-height: 1.5;
        max-height: 0;
        overflow: hidden;
        transition: max-height 0.4s ease, opacity 0.4s ease;
        opacity: 0;
        margin: 0;
    }

    .ecosystem-section .card.active .card-description {
        max-height: 150px;
        opacity: 1;
        margin-bottom: 20px;
    }

    .ecosystem-section .learn-more {
        color: var(--accent-green);
        text-decoration: none;
        font-size: 14px;
        display: flex;
        align-items: center;
        gap: 5px;
        opacity: 0;
        transition: opacity 0.4s ease;
    }

    .ecosystem-section .card.active .learn-more {
        opacity: 1;
    }

    .ecosystem-section .pagination {
        display: flex;
        justify-content: center;
        gap: 10px;
        margin-top: 40px;
    }

    .ecosystem-section .dot {
        width: 8px;
        height: 8px;
        background: rgba(255,255,255,0.2);
        border-radius: 50%;
        transition: all 0.3s ease;
        cursor: pointer;
    }

    .ecosystem-section .dot.active {
        width: 24px;
        border-radius: 10px;
        background: var(--accent-green);
    }

    /* Arc layout positions */
    .ecosystem-section .card.pos-left-2 { transform: translateX(-50vw) translateY(120px) rotateZ(-5deg) scale(1); z-index: 2; opacity: 0.2; }
    .ecosystem-section .card.pos-left-1 { transform: translateX(-25vw) translateY(40px) rotateZ(-3deg) scale(1); z-index: 5; }
    .ecosystem-section .card.pos-center { transform: translateX(0) translateY(0) rotateY(0) scale(1.1); z-index: 10; }
    .ecosystem-section .card.pos-right-1 { transform: translateX(25vw) translateY(40px) rotateZ(3deg) scale(1); z-index: 5; }
    .ecosystem-section .card.pos-right-2 { transform: translateX(50vw) translateY(120px) rotateZ(5deg) scale(1); z-index: 2; opacity: 0.2; }
    
    .ecosystem-section .card.pos-hidden { transform: scale(0); opacity: 0; z-index: 0; pointer-events: none; }

    .ecosystem-section .arc-line {
        position: absolute;
        bottom: -210px;
        left: 50%;
        transform: translateX(-50%);
        width: 90%;
        height: 200px;
        border-top: 1px solid rgba(255,255,255,0.1);
        border-radius: 60% / 100px 100px 0 0;
        z-index: 0;
        pointer-events: none;
    }
    
    .ecosystem-section .corner-marks {
        position: absolute;
        top: 20px;
        left: 20px;
        right: 20px;
        bottom: 20px;
        pointer-events: none;
    }
    
    .ecosystem-section .corner-mark {
        position: absolute;
        width: 10px;
        height: 10px;
        border-color: rgba(255,255,255,0.2);
        border-style: solid;
    }
    
    .ecosystem-section .card.active .corner-mark {
        border-color: rgba(0, 170, 80, 0.4);
    }
    
    .ecosystem-section .top-left { top: 0; left: 0; border-width: 1px 0 0 1px; border-top-left-radius: 10px; }
    .ecosystem-section .top-right { top: 0; right: 0; border-width: 1px 1px 0 0; border-top-right-radius: 10px; }
    .ecosystem-section .bottom-left { bottom: 0; left: 0; border-width: 0 0 1px 1px; border-bottom-left-radius: 10px; }
    .ecosystem-section .bottom-right { bottom: 0; right: 0; border-width: 0 1px 1px 0; border-bottom-right-radius: 10px; }

    @media (max-width: 768px) {
        .ecosystem-section .header-content {
            flex-direction: column;
            padding: 0 5%;
            margin-bottom: 40px;
        }
        .ecosystem-section .title {
            font-size: 32px;
            margin-bottom: 20px;
        }
        .ecosystem-section .card {
            width: 280px;
            height: 380px;
            padding: 20px;
        }
        .ecosystem-section .card.pos-left-1 { transform: translateX(-35vw) translateY(40px) scale(0.8); }
        .ecosystem-section .card.pos-right-1 { transform: translateX(35vw) translateY(40px) scale(0.8); }
        .ecosystem-section .card.pos-left-2, .ecosystem-section .card.pos-right-2 { display: none; }
    }
</style>

<script>
(function() {
    const container = document.getElementById('ecosystem-cards-container');
    if (!container) return;
    
    const cards = Array.from(container.querySelectorAll('.card'));
    const pagination = document.getElementById('ecosystem-pagination');
    if (!pagination) return;
    
    let currentIndex = Math.floor(cards.length / 2);

    function init() {
        // Create pagination dots
        cards.forEach((_, i) => {
            const dot = document.createElement('div');
            dot.classList.add('dot');
            if (i === currentIndex) dot.classList.add('active');
            dot.addEventListener('click', () => {
                currentIndex = i;
                updateCards();
            });
            pagination.appendChild(dot);
        });

        // Add click events to cards
        cards.forEach((card, i) => {
            card.addEventListener('click', () => {
                if (i !== currentIndex) {
                    currentIndex = i;
                    updateCards();
                }
            });
        });

        updateCards();
    }

    function updateCards() {
        const dots = pagination.querySelectorAll('.dot');

        cards.forEach((card, i) => {
            card.className = 'card'; // Reset
            if (dots[i]) dots[i].classList.remove('active');

            let diff = i - currentIndex;
            
            if (diff === 0) {
                card.classList.add('active', 'pos-center');
                if (dots[i]) dots[i].classList.add('active');
            } else if (diff === -1) {
                card.classList.add('pos-left-1');
            } else if (diff === -2) {
                card.classList.add('pos-left-2');
            } else if (diff === 1) {
                card.classList.add('pos-right-1');
            } else if (diff === 2) {
                card.classList.add('pos-right-2');
            } else {
                card.classList.add('pos-hidden');
            }
        });
    }

    init();
})();
</script>

<?php endif; ?>




